### ISSUE TITLE
User관련 Domain 수정 ( 사용자가 추위, 더위 타는지 정보 추가)

### ISSUE THREAD

**Issue by timointhebush** [dnd-side-project/dnd-5th-4-backend#14]
## 🤷 이슈 내용
- 7월 25일(일) 환의님께서 참석 못하셨던 회의에서 나온 이야기였습니다!
- 팀원분들이 사용자가 추위를 타는지, 더위를 타는지 정보도 기입하면 좋을 것 같다고 하셔서 해당 내용을 담을 도메인을 수정해야할 것 같습니다!

## ✨ 기대 결과
- User class에 해당 내용을 담을 필드를 추가
- 추위 타는지, 더위 타는지 -> 해당 Enum class 생성

## 📸 스크린샷
![image](https://user-images.githubusercontent.com/33304833/127178958-be062d3d-3c26-4da0-802a-50cd41f8ee3d.png)

**Comment by whanhee97** [comment]
네 그럼 제가 수정하겠습니다
