### ISSUE TITLE
개발 환경 세팅, Domain 수정 관련 궁금증, 논의

### ISSUE THREAD

**Issue by timointhebush** [dnd-side-project/dnd-5th-4-backend#15]
### `application.yml`파일 관련
- mysql설정하면서 궁금한 점 이었는데, 관련 정보들이 `application.yml`파일에 담겨 있는데(root, pw 등) 해당 파일이 git 에 같이 업로드 되더라구요. 보통 같이 개발할 땐 이 부분을 어떻게 처리하는지 궁금합니다!
### Domain 관련
- JPA 강의를 보니까 대부분 `fetch = FetchType.LAZY` 로 지연로딩으로 설정해놓더라구요! 저희는 이거 설정 안해도 괜찮을지..? 강의 듣다 생각나서 올려봅니다!

**Comment by whanhee97** [comment]
fetch는 LAZY로 해야할거 같고
yml파일은 gitignore로 제외를 시켜야할 것 같습니다
