### ISSUE TITLE
평가 조회 기능 구현

### ISSUE THREAD

**Issue by whanhee97** [dnd-side-project/dnd-5th-4-backend#37]
## 🤷 이슈 내용

- 다른 사람의 평가를 가져오는 기능
- 내가 기록한 평가 조회하는 기능 구현
## ✨ 기대 결과

다른 사람이 그 날씨에 평가한 기록들을 랜덤으로 가져온다.
내가 그날 기록한 평가를 볼 수 있다.

## 📸 스크린샷

이슈에 해당하는 부분을 보여주세요.

**Comment by timointhebush** [comment]
나의 평가, 남들의 평가 조회
